### PR TITLE
feat: use Ctrl + mouse wheel to change the font

### PR DESCRIPTION
**Pull request by ouuan**

### CODE REVIEW

**Comment by sonulohani** [comment]
Hi @ouuan 

I can verify from visual studio 2019 and vscode that when we zoom in or zoom out, it generally zoom-in/out the viewport and not increase/decrease font size. 

Reference link for zoom-in/out the widget:- https://stackoverflow.com/questions/6650219/zooming-function-on-a-qwidget

**Comment by ouuan** [comment]
@coder3101 @neko-para Any review?

**Comment by coder3101** [comment]
> I can verify from visual studio 2019 and vscode that when we zoom in or zoom out, it generally zoom-in/out the viewport and not increase/decrease font size.

It is true but what is the problem with increasing or decreasing the font size?

**Comment by neko-para** [comment]
I think it's ok to change font size directly.

**Comment by sonulohani** [comment]
Hi @ouuan , @coder3101 , @neko-para 

Anyway this PR got merged but I want to point out that you can't increase font value in floats and what I have seen is that sometimes for small font size like consolas, between pt. 11 and 12 I get my sweet spot at 11.5pt which I can set it using font settings. That's where zoom comes handy. Its all about providing better user experience.

**Pull request merged**
