### PR TITLE
+ fixed wording and markdown list format

### PR DESCRIPTION
**Pull request by moodyhunter**
don't know what's going on there

### CODE REVIEW

**Comment by ouuan** [comment]
Markdown doesn't require correct numbers in ordered lists.

**Comment by ouuan** [comment]
And we don't update the README for this fork. In fact, this was not intended to be shared with others.

**Comment by moodyhunter** [comment]
if that's the case in which the project was not "intended to be shared with others", it'll be better if there's a clear notice so that not wasting the external contributors' time opening PRs. Not accepting a typo in README is non-constructive.

**Comment by ouuan** [comment]
We have a notice in the repository description: "Now deprecated and will no longer be maintained by the CP Editor team."

**Comment by ouuan** [comment]
> Not accepting a typo in README is non-constructive.

I didn't notice those typos at first because the most noticeable change was the list. And then I noticed the typos after closing this but I don't think it matters much in a deprecated fork.

**Pull request closed without merging**
