### PR TITLE
style: Unindent when typing "}"

### PR DESCRIPTION
**Pull request by sonulohani**

### CODE REVIEW

**Comment by ouuan** [comment]
1. It should be optional. See `m_autoIndentation` as an example.
2. In this way, there are two operations, thus needs two undos to undo the whole operation. I forgot this in [this comment](https://github.com/cpeditor/cpeditor/issues/393#issuecomment-640445057). So you need to unindent without the `unindent()` function, and make sure it's done in a single operation.
3. You should format your codes with Clang Format 9 or Clang Format 10. If you have problems installing Clang Format, we can help you to format the codes before merging.

**Comment by sonulohani** [comment]
>     1. It should be optional. See `m_autoIndentation` as an example.
> 
>     2. In this way, there are two operations, thus needs two undos to undo the whole operation. I forgot this in [this comment](https://github.com/cpeditor/cpeditor/issues/393#issuecomment-640445057). So you need to unindent without the `unindent()` function, and make sure it's done in a single operation.
> 
>     3. You should format your codes with Clang Format 9 or Clang Format 10. If you have problems installing Clang Format, we can help you to format the codes before merging.

Hi @ouuan 

Thanks for the review comment. Do you mean I need to write my own unindent method.

**Comment by ouuan** [comment]
I said "See `m_autoIndentation` as an example", didn't let you to use `m_autoIndentation` for this operation. However, `m_autoIndentation` is somehow suitable for this operation, what do you think?

> Do you mean I need to write my own unindent method.

Not a method, just codes.

> I am still confused in this:- _"make sure it's done in a single operation."_

"a single operation" basically means a single modification to the document. You can press <kbd>Ctrl+Z</kbd> to see how many operations there are.

**Comment by sonulohani** [comment]
This will take some time, as I recently formatted my system and installed windows. Excited to experiment WSL2.

**Comment by sonulohani** [comment]
Since i am using QT 5.14 thus now I am getting error in QProcess::splitCommand. @ouuan Could you please fix the rest of the things. 
Thanks

**Comment by ouuan** [comment]
> Since i am using QT 5.14 thus now I am getting error in QProcess::splitCommand. @ouuan Could you please fix the rest of the things as I am using internet with limited data and can't install Qt 5.15 now.
> Thanks

Did you meet any difficulty when installing Qt 5.15?

**Comment by coder3101** [comment]
QCodeEditor does not uses `QProcess::split command(...)`

If you are testing Code Editor by building CP Editor, you can use examples in this repository to test things instead.

**Comment by ouuan** [comment]
Or you can test on older commits, for example, you can `git checkout b0712ef`.

**Comment by sonulohani** [comment]
> Or you can test on older commits of CP Editor, for example, you can `git checkout b0712ef`.

Will do this way. Thanks for the quick reply.

**Comment by sonulohani** [comment]
Hi @ouuan ,

I tested and the unindent is done in one operation. No need to add any new changes.

**Comment by ouuan** [comment]
> Hi @ouuan ,
> 
> I tested and the unindent is done in one operation. No need to add any new changes.

I tested on Arch Linux and it's done in two operations, i.e. it needs two <kbd>Ctrl+Z</kbd> to undo after typing `}`.

**Comment by sonulohani** [comment]
> 
> 
> > Hi @ouuan ,
> > I tested and the unindent is done in one operation. No need to add any new changes.
> 
> I tested on Arch Linux and it's done in two operations, i.e. it needs two Ctrl+Z to undo after typing `}`.

Yeah 3 days back I tested in manjaro and took 2 operation to undo however in windows it takes only one operation.

**Comment by sonulohani** [comment]
Hi @ouuan,

I installed windows seeing that wsl2 has made an impressive progress in running linux but for now I can't use it to develop/test gui apps. In windows the undo is working fine, however I can't test in linux. Could you please help me in this regards.

**Comment by ouuan** [comment]
> Hi @ouuan,
> 
> I installed windows seeing that wsl2 has made an impressive progress in running linux but for now I can't use it to develop/test gui apps. In windows the undo is working fine, however I can't test in linux. Could you please help me in this regards.

Maybe you can try to work on other issues, and I will work on this instead?

**Comment by sonulohani** [comment]
Hi @ouuan 

I will work on other issues then. Thanks for taking it forward.

**Pull request closed without merging**
