### PR TITLE
Added a simple JS highlighter

### PR DESCRIPTION
**Pull request by BeardedBeaver**
A quick JS syntax highlighter was added based on CXX highlighter and basic rules

### CODE REVIEW

**Comment by BeardedBeaver** [comment]
> LGTM, thanks! It will be better if you can add a JS code sample, if you aren't willing to add it, you can tell me and I'll merge this as well.

Thank you for the feedback. I implemented a JS support for my Qt-based application which is scriptable with QJSEngine. I have code examples from it but it's not exactly JS and probably won't work as a legit example. I think it'd be better to add a valid example later.

**Comment by ouuan** [comment]
> I think it'd be better to add a valid example later.

I don't really get this. So do you want us to merge this first, or you'll add a "valid example" soon?

**Comment by BeardedBeaver** [comment]
I added a sample JS code

**Comment by BeardedBeaver** [comment]
Integrated it in my program, works and looks great! 
codeeditor

**Pull request merged**
