### PR TITLE
Add Indentation guide in editor

### PR DESCRIPTION
**Pull request by sonulohani**
Issue: https://github.com/cpeditor/cpeditor/issues/413

Here is the screenshot after adding indent guide

image

### CODE REVIEW

**Comment by sonulohani** [comment]
This PR is still in **WIP**. If I load big source file the editor hung. We need to paint only the visible area. Currently we are painting the whole region.

**Comment by ouuan** [comment]
It seems that you added #22 in this PR :thinking: Is that a mistake?

**Comment by sonulohani** [comment]
@ouuan 

Thanks for notifying. I will fix this tomorrow.

**Comment by sonulohani** [comment]
I will create new PR.

**Pull request closed without merging**
